language: node_js
node_js:
- '8'
dist: trusty
sudo: required
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  chrome: stable
cache:
  directories:
  - node_modules
env:
- NODE_ENV=ci
install:
- npm install
script:
- nohup npm run start &
- sleep 3
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: gLAeG0AB1BUkxPoRbZNzFHhETHvEhpYjrvVL+xKGhODlGeOvGUddDPvLouKrImHtIkaJ5ud0L1mvMwL1ts64bFd8jkfs/gR/m+hcI/YgZowUo2AwblB+2Ocl17ZTcsEaaZ5vXTooWKo0bE84nUhz5VQYGhCcLS5oXDWzB4c65CqrM/4T3cpfMjp5B5ImYEnJoBh//lAidrYvvnNWCaeDiUz7NzPgMdGrItXXQJ+H74tIJE/bXd/OruQN5dXReZRt8LdkI1ZQuS6P/UlPjXe2sf/kbAyi5CZtpCOM7Mr+99/UUyeA2dwePuVJuZwKg8rfE02GF5Tdk/HdxpgkHtEc4BV8XK9NORy9fEJSEJXAxL9Wg0fiOqYqFR4cd4Tpi9oHl2oXd2fty8yT6koBM1mP7jpMfygT9/7gTBKVQyKkFJnAxo10oI+a7mCF7WsfhBzchUg465AoPalpOdlV414g65+jetzkNzckQv9B1zJ1m5V1dsU3BUicyrqeWEeFo+1ljj2Haj26iTgsaLcsIE8I98CtG6gFOlJokBbS4QqzM7n2NvBLyCz9jQGvw5Tsf2pqU8fXPUXSTFAsRXutDuw2pyTaIeXgXRuBJ4EJl74TqonrmrhM6+m/88oqOz7wQFAQsAKLC0MqfnGvG3Qf0oAd8UY21g7oQ2EMnAgFbX2S10k=
  app: wicecrm-api
  skip_cleanup: true
