// function customOrganization(organization) {
//   const customOrganizationFormat = {
//     rowid: organization.rowid,
//     last_update: organization.last_update,
//     name: organization.name,
//     email: organization.email,
//     phone: organization.phone,
//     fax: organization.fax,
//     street: organization.street,
//     street_number: organization.street_number,
//     zip_code: organization.zip_code,
//     p_o_box: organization.p_o_box,
//     town: organization.town,
//     state: organization.state,
//     country: organization.country,
//
//   };
//   return customOrganizationFormat;
// }
//
// module.exports = { customOrganization };

/* eslint camelcase: "off" */

function customOrganization(organization) {
  const {
    zero_tax_default,
    show_in_public_view,
    charset_may_be_modified,
    add_entry_link,
    new_document_link,
    section_name,
    notes_displayed,
    company_delivery_address_id,
    cp_or_company_table_selected,
    assign_link,
    demo_mode,
    tablink_invoices,
    current_theme,
    import_key,
    searchstring,
    soc_checked,
    shop_discount,
    change_log_available,
    https,
    js_unhide_html_files,
    used_software,
    public_access_enabled_for_address_data,
    public_access_key,
    found_entries_not_needed,
    general_selected,
    showtabs,
    current_users_asterisk_extension,
    menu_link_prefix,
    delivery_address_id,
    tablink_documents,
    tickets_available,
    global_config,
    status_time,
    js_hide_html_files,
    class_name,
    protocol,
    documents_displayed,
    new_ticket,
    history_log,
    google_maps_api_key,
    tablink_appointments,
    sales_tax_ident,
    selected_tablename,
    new_note_link,
    is_admin,
    searchcol_select,
    assigned_type_id,
    email_check_result,
    employee_assigned,
    projects_displayed,
    invoices_displayed,
    dpf_log_url,
    assigned_type_obsolete,
    relations_image,
    wp_contact_remote_addr,
    edit_link,
    mandant_color,
    tablink_notes,
    hide_messaging_and_forums,
    tablink_projects,
    do_not_display_anymore_in_duplicate_list_in_wp_contact,
    hide_kbase,
    copy_link,
    session_data,
    map_link,
    line,
    appointments_do_not_offer_listall,
    use_webvis8_page_links,
    user_column_152,
    simplesstring,
    styles,
    company_table_selected,
    assigned_to_obsolete,
    suburb,
    google_geocode_api_key,
    oldstatus,
    ...customOrganizationFormat
  } = organization;
  return customOrganizationFormat;
}

module.exports = { customOrganization };
